name = "optimizemyresume-pro"
compatibility_date = "2024-01-01"

# Cloudflare Pages 配置
pages_build_output_dir = "out"

[env.production]
name = "optimizemyresume-pro"

[build]
command = "npm run build"